name: gemma-3-270m
backend: hf                  
hf_repo: google/gemma-3-270m 
dtype: float32               
device: cpu           # CPU 환경
max_model_len: 2048     # Gemma-3 270M의 기본 컨텍스트 길이

generation:
  max_tokens: 256       # 한 번에 생성할 최대 토큰 수
  temperature: 0.8        # 샘플링 다양성 (0.7~1.0 권장)
  top_p: 0.95             # nucleus sampling
  repetition_penalty: 1.05   # 반복 억제

resources:
  num_threads: 8          # i9 CPU 스레드 활용
  ram_requirement: 8GB      # 최소 RAM

logging:
  level: INFO
  save_prompts: true         # 프롬프트 로깅
  save_responses: true       # 응답 저장
